### ISSUE TITLE
Guild Wars 2 not installed

### ISSUE THREAD

**Issue by FregrinZ** [Mixaill/galaxy-integration-gw2#3]
Hello,

Not sure if i installed this correctly but says game isnt installed and cannot find way to add it properly ? So there is no information or play button in GOG ?

If i click install says not compatible ?

**Comment by Mixaill** [comment]
Not implemented yet.

**Comment by Mixaill** [comment]
Fixed in 789704cdf84c2d90739a78cb775cc0270bb24a54
