### ISSUE TITLE
Achievement Support

### ISSUE THREAD

**Issue by Darkenend** [Mixaill/galaxy-integration-gw2#4]
Could we have achievements support down the road?

[Here's a link to the API info about achievements](https://wiki.guildwars2.com/wiki/API:2/account/achievements).

**Comment by Mixaill** [comment]
Yeah, it in progress

**Comment by Mixaill** [comment]
Added in https://github.com/Mixaill/galaxy-integration-gw2/commit/91e359cdf5ec2b56002d02752231540c98fc4a24

**Comment by Darkenend** [comment]
I reported this on the GoG side, and got [this](https://mantis2.gog.com/view.php?id=12317) reply, maybe it's useful.

**Comment by FriendsOfGalaxy** [comment]
@Mixaill 

Hey,

Galaxy first needs definitions of achievements (all achievements which are possible to unlock in the game) before they can be reported and shown for a given platform.

Please send us an email to friendsofgalaxy@gmail.com with a json file containing up-to-date achievements for Guild Wars 2 in a form similar to this.

```
{
        "release_per_platform_id": "{platform_id}_{game_id}",
        "name": "Achievement_name",
        "description": "Achievement_description.",
        "api_key": "achievement_api_key",
        "image_url_unlocked": "image_achievement_unlocked",
        "image_url_locked": "image_achievement_locked"
},
```

Other possibility is sending us an url or an endpoint which provides similar information.

Bear in mind not all of those are required and in worst case scenario api_key and name would suffice.

We will pass the provided information to GOG and hopefully get those achievements working as soon as possible.

Hope this helps!

**Comment by FriendsOfGalaxy** [comment]
Hey,

I've checked today and my achievements have started showing up (it took around 2 minutes for all of them to show up, game has a lot of achievements). @Darkenend  @Mixaill

**Comment by Mixaill** [comment]
Confirm it.
