### ISSUE TITLE
Add functionality to Install method

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [Mixaill/galaxy-integration-gw2#5]
Hey, 

currently there is no way to install, or start the installation process of GW2 through its integration, my suggestion would be to instead of returning None at least open up the 'https://account.arena.net/welcome' webpage in default browser which has this screen 
![image](https://user-images.githubusercontent.com/48480506/66578415-5751e380-eb7b-11e9-8510-e121d6ab1ae0.png)

This would be a quick change from this:
```
 async def install_game(self, game_id):
        if game_id != self.GAME_ID:
            logging.warn('plugin/install_game: unknown game_id %s' % game_id)
            return
```

to something like this:
```
import webbrowser
 async def install_game(self, game_id):
        webbrowser.open('https://account.arena.net/welcome')
```

Hope this is of help.

**Comment by Mixaill** [comment]
Fixed in 789704cdf84c2d90739a78cb775cc0270bb24a54
