### ISSUE TITLE
FOG Fork Autoupdate Request

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [Mixaill/galaxy-integration-gw2#7]
Hey, 

we're planning on creating a fork/autoupdate system with selected plugins. This would allow us to create a list of curated and reviewed plugins which could be of use to GOG Galaxy people.

Of course you will be credited as the creator and developer of the plugin in the fork readme and possibly other places.

Before we do that we need to ask you to create a `fog_release` branch which would contain only your plugin code, `manifest.json` and a `requirements.txt` file (without `3rdparty` directory). For Github releases, we will include whole directory where `manifest.json` is placed and build dependencies directly there. This is for easier code verification. Code for repo synchronization can be found here: https://github.com/FriendsOfGalaxy/galaxy-integrations-updater

**Comment by Mixaill** [comment]
Please check

**Comment by FriendsOfGalaxy** [comment]
Works perfectly, thanks! Fork has been synchronized properly tonight: https://github.com/FriendsOfGalaxy/galaxy-integration-gw2/pull/1
After any version bump in manifest (on `fog_release` branch) pull request will be created (or updated) on our side and we will merge it after manual security review.
