### ISSUE TITLE
"API key is not valid" for fresh account 

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [Mixaill/galaxy-integration-gw2#8]
When connecting API key for a account that was never in the game api returns:
{'text': 'ErrBadData'}
so the plugin shows error: "API key is not valid". It is probably not the plugin problem but maybe you can bypass it somehow and pass bug request on to api developers?

This affects only those who just begin their gw2 journey, so not very common right now, but in being a FoG fork may make it more popular and new gw2 users will waste time trying to figure out what is going wrong, try to change API permission scope like me ect.

BTW please write what minimal permission scope is needed for plugin to run properly.

**Comment by Mixaill** [comment]
@FriendsOfGalaxy improved description for error and clarified permission scope

**Comment by FriendsOfGalaxy** [comment]
Thanks, that should be enough
